### ISSUE TITLE
loadurl loadfile

### ISSUE THREAD

**Issue by mlmdflr** [youliso/electron-template#12]
希望能在加载url设置用户代理等功能

下面是我的

![image](https://user-images.githubusercontent.com/93173537/140496675-d73f1821-3c3b-45bc-84ea-7c152a06e142.png)

![image](https://user-images.githubusercontent.com/93173537/140496621-bcb7c278-d0eb-43b1-ba10-7fbb49fc5378.png)

![image](https://user-images.githubusercontent.com/93173537/140496460-e8d936f6-06c0-4583-ac73-5e416fc015eb.png)

**Comment by youliso** [comment]
f252773dcf87d60e326b41d5cb4490d9de37b847
