### ISSUE TITLE
在渲染进程中使用lib中的net报错

### ISSUE THREAD

**Issue by SpiritGuy** [youliso/electron-template#7]
请问是只能在主进程中使用吗
![微信截图_20210831094524](https://user-images.githubusercontent.com/59172943/131428361-5c0bf081-83a1-4daa-89e5-18088f8deb14.png)

**Comment by youliso** [comment]
[参考主分支此处](https://github.com/youliso/electron-template/blob/master/build/script/webpack.base.config.js#L11)

**Comment by SpiritGuy** [comment]
你好,我如参考一样添加了相同配置,但是渲染进程会报这个错
![image](https://user-images.githubusercontent.com/59172943/131434082-b02cef34-e227-4ace-a57b-026fda239f62.png)

**Comment by SpiritGuy** [comment]
这是我的配置
![image](https://user-images.githubusercontent.com/59172943/131434370-e7801ed3-757b-444e-b29f-e60e76aa66fa.png)
![image](https://user-images.githubusercontent.com/59172943/131434420-8d0759a9-73de-4ecc-8e8d-143039e23d16.png)

**Comment by youliso** [comment]
> 你好,我如参考一样添加了相同配置,但是渲染进程会报这个错
> ![image](https://user-images.githubusercontent.com/59172943/131434082-b02cef34-e227-4ace-a57b-026fda239f62.png)

更新下 net.ts  [主分支net.ts](https://github.com/youliso/electron-template/blob/master/src/lib/net.ts)

**Comment by SpiritGuy** [comment]
可以了,我是用的vue分支 ,看下您最新的代码webpack是没进行修改的,我删掉就好了

**Comment by youliso** [comment]
是有问题的，打包后主进程abortController会报错的，正在解决

**Comment by youliso** [comment]
已解决查看我最新的提交
[fix bug](https://github.com/youliso/electron-template/commit/18ab53d97b8d347865f5d781a6df83afc52a0f00)

**Comment by SpiritGuy** [comment]
对了大佬,我如果在net.ts 中使用代理,也就是这两个,应该做哪些操作呢,我现在直接用是报错的
![image](https://user-images.githubusercontent.com/59172943/131438102-50294fd3-03fa-4d62-a4d8-e17a6cfc0654.png)

**Comment by youliso** [comment]
因为net是主、渲染进程共用的，你得先看这两个是不是同时支持node和web引入。
